// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message type constants
type VsockMessage_Type int32

const (
	VsockMessage_TYPE_UNSPECIFIED VsockMessage_Type = 0
	VsockMessage_TYPE_INIT        VsockMessage_Type = 1
	VsockMessage_TYPE_EXEC        VsockMessage_Type = 2
	VsockMessage_TYPE_RESP        VsockMessage_Type = 3
	VsockMessage_TYPE_PING        VsockMessage_Type = 4
	VsockMessage_TYPE_STOP        VsockMessage_Type = 5
	VsockMessage_TYPE_RELOAD      VsockMessage_Type = 6
	VsockMessage_TYPE_STREAM      VsockMessage_Type = 7
)

// Enum value maps for VsockMessage_Type.
var (
	VsockMessage_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "TYPE_INIT",
		2: "TYPE_EXEC",
		3: "TYPE_RESP",
		4: "TYPE_PING",
		5: "TYPE_STOP",
		6: "TYPE_RELOAD",
		7: "TYPE_STREAM",
	}
	VsockMessage_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_INIT":        1,
		"TYPE_EXEC":        2,
		"TYPE_RESP":        3,
		"TYPE_PING":        4,
		"TYPE_STOP":        5,
		"TYPE_RELOAD":      6,
		"TYPE_STREAM":      7,
	}
)

func (x VsockMessage_Type) Enum() *VsockMessage_Type {
	p := new(VsockMessage_Type)
	*p = x
	return p
}

func (x VsockMessage_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VsockMessage_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (VsockMessage_Type) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x VsockMessage_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VsockMessage_Type.Descriptor instead.
func (VsockMessage_Type) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0, 0}
}

// VsockMessage is the top-level envelope for all host <-> agent communication
// over the vsock channel. It replaces the JSON-based VsockMessage struct.
type VsockMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  VsockMessage_Type      `protobuf:"varint,1,opt,name=type,proto3,enum=nova.agent.v1.VsockMessage_Type" json:"type,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*VsockMessage_Init
	//	*VsockMessage_Exec
	//	*VsockMessage_Resp
	//	*VsockMessage_Reload
	//	*VsockMessage_StreamChunk
	Payload       isVsockMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VsockMessage) Reset() {
	*x = VsockMessage{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VsockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VsockMessage) ProtoMessage() {}

func (x *VsockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VsockMessage.ProtoReflect.Descriptor instead.
func (*VsockMessage) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *VsockMessage) GetType() VsockMessage_Type {
	if x != nil {
		return x.Type
	}
	return VsockMessage_TYPE_UNSPECIFIED
}

func (x *VsockMessage) GetPayload() isVsockMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *VsockMessage) GetInit() *InitPayload {
	if x != nil {
		if x, ok := x.Payload.(*VsockMessage_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *VsockMessage) GetExec() *ExecPayload {
	if x != nil {
		if x, ok := x.Payload.(*VsockMessage_Exec); ok {
			return x.Exec
		}
	}
	return nil
}

func (x *VsockMessage) GetResp() *RespPayload {
	if x != nil {
		if x, ok := x.Payload.(*VsockMessage_Resp); ok {
			return x.Resp
		}
	}
	return nil
}

func (x *VsockMessage) GetReload() *ReloadPayload {
	if x != nil {
		if x, ok := x.Payload.(*VsockMessage_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *VsockMessage) GetStreamChunk() *StreamChunkPayload {
	if x != nil {
		if x, ok := x.Payload.(*VsockMessage_StreamChunk); ok {
			return x.StreamChunk
		}
	}
	return nil
}

type isVsockMessage_Payload interface {
	isVsockMessage_Payload()
}

type VsockMessage_Init struct {
	Init *InitPayload `protobuf:"bytes,2,opt,name=init,proto3,oneof"`
}

type VsockMessage_Exec struct {
	Exec *ExecPayload `protobuf:"bytes,3,opt,name=exec,proto3,oneof"`
}

type VsockMessage_Resp struct {
	Resp *RespPayload `protobuf:"bytes,4,opt,name=resp,proto3,oneof"`
}

type VsockMessage_Reload struct {
	Reload *ReloadPayload `protobuf:"bytes,5,opt,name=reload,proto3,oneof"`
}

type VsockMessage_StreamChunk struct {
	StreamChunk *StreamChunkPayload `protobuf:"bytes,6,opt,name=stream_chunk,json=streamChunk,proto3,oneof"`
}

func (*VsockMessage_Init) isVsockMessage_Payload() {}

func (*VsockMessage_Exec) isVsockMessage_Payload() {}

func (*VsockMessage_Resp) isVsockMessage_Payload() {}

func (*VsockMessage_Reload) isVsockMessage_Payload() {}

func (*VsockMessage_StreamChunk) isVsockMessage_Payload() {}

// InitPayload initializes the agent with function configuration
type InitPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Runtime         string                 `protobuf:"bytes,1,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Handler         string                 `protobuf:"bytes,2,opt,name=handler,proto3" json:"handler,omitempty"`
	EnvVars         map[string]string      `protobuf:"bytes,3,rep,name=env_vars,json=envVars,proto3" json:"env_vars,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Command         []string               `protobuf:"bytes,4,rep,name=command,proto3" json:"command,omitempty"`
	Extension       string                 `protobuf:"bytes,5,opt,name=extension,proto3" json:"extension,omitempty"`
	Mode            string                 `protobuf:"bytes,6,opt,name=mode,proto3" json:"mode,omitempty"` // "process" or "persistent"
	FunctionName    string                 `protobuf:"bytes,7,opt,name=function_name,json=functionName,proto3" json:"function_name,omitempty"`
	FunctionVersion int32                  `protobuf:"varint,8,opt,name=function_version,json=functionVersion,proto3" json:"function_version,omitempty"`
	MemoryMb        int32                  `protobuf:"varint,9,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	TimeoutS        int32                  `protobuf:"varint,10,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	LayerCount      int32                  `protobuf:"varint,11,opt,name=layer_count,json=layerCount,proto3" json:"layer_count,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InitPayload) Reset() {
	*x = InitPayload{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitPayload) ProtoMessage() {}

func (x *InitPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitPayload.ProtoReflect.Descriptor instead.
func (*InitPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *InitPayload) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *InitPayload) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *InitPayload) GetEnvVars() map[string]string {
	if x != nil {
		return x.EnvVars
	}
	return nil
}

func (x *InitPayload) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *InitPayload) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *InitPayload) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *InitPayload) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *InitPayload) GetFunctionVersion() int32 {
	if x != nil {
		return x.FunctionVersion
	}
	return 0
}

func (x *InitPayload) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *InitPayload) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *InitPayload) GetLayerCount() int32 {
	if x != nil {
		return x.LayerCount
	}
	return 0
}

// ExecPayload sends a function invocation request
type ExecPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"` // JSON payload as raw bytes
	TimeoutS      int32                  `protobuf:"varint,3,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	TraceParent   string                 `protobuf:"bytes,4,opt,name=trace_parent,json=traceParent,proto3" json:"trace_parent,omitempty"` // W3C TraceContext traceparent
	TraceState    string                 `protobuf:"bytes,5,opt,name=trace_state,json=traceState,proto3" json:"trace_state,omitempty"`    // W3C TraceContext tracestate
	Stream        bool                   `protobuf:"varint,6,opt,name=stream,proto3" json:"stream,omitempty"`                             // Enable streaming response
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecPayload) Reset() {
	*x = ExecPayload{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecPayload) ProtoMessage() {}

func (x *ExecPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecPayload.ProtoReflect.Descriptor instead.
func (*ExecPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *ExecPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecPayload) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecPayload) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *ExecPayload) GetTraceParent() string {
	if x != nil {
		return x.TraceParent
	}
	return ""
}

func (x *ExecPayload) GetTraceState() string {
	if x != nil {
		return x.TraceState
	}
	return ""
}

func (x *ExecPayload) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

// RespPayload returns the result of a function invocation
type RespPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // JSON response as raw bytes
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Stdout        string                 `protobuf:"bytes,5,opt,name=stdout,proto3" json:"stdout,omitempty"` // Captured stdout
	Stderr        string                 `protobuf:"bytes,6,opt,name=stderr,proto3" json:"stderr,omitempty"` // Captured stderr
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespPayload) Reset() {
	*x = RespPayload{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespPayload) ProtoMessage() {}

func (x *RespPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespPayload.ProtoReflect.Descriptor instead.
func (*RespPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RespPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RespPayload) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *RespPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RespPayload) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RespPayload) GetStdout() string {
	if x != nil {
		return x.Stdout
	}
	return ""
}

func (x *RespPayload) GetStderr() string {
	if x != nil {
		return x.Stderr
	}
	return ""
}

// ReloadPayload hot-reloads function code files
type ReloadPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         map[string][]byte      `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // relative path -> file content
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadPayload) Reset() {
	*x = ReloadPayload{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadPayload) ProtoMessage() {}

func (x *ReloadPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadPayload.ProtoReflect.Descriptor instead.
func (*ReloadPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ReloadPayload) GetFiles() map[string][]byte {
	if x != nil {
		return x.Files
	}
	return nil
}

// StreamChunkPayload sends a chunk of streaming response data
type StreamChunkPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`                    // Chunk of data
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"` // True if this is the final chunk
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`                  // Error message if execution failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamChunkPayload) Reset() {
	*x = StreamChunkPayload{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamChunkPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamChunkPayload) ProtoMessage() {}

func (x *StreamChunkPayload) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamChunkPayload.ProtoReflect.Descriptor instead.
func (*StreamChunkPayload) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *StreamChunkPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *StreamChunkPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *StreamChunkPayload) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

func (x *StreamChunkPayload) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\rnova.agent.v1\"\xf1\x03\n" +
	"\fVsockMessage\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .nova.agent.v1.VsockMessage.TypeR\x04type\x120\n" +
	"\x04init\x18\x02 \x01(\v2\x1a.nova.agent.v1.InitPayloadH\x00R\x04init\x120\n" +
	"\x04exec\x18\x03 \x01(\v2\x1a.nova.agent.v1.ExecPayloadH\x00R\x04exec\x120\n" +
	"\x04resp\x18\x04 \x01(\v2\x1a.nova.agent.v1.RespPayloadH\x00R\x04resp\x126\n" +
	"\x06reload\x18\x05 \x01(\v2\x1c.nova.agent.v1.ReloadPayloadH\x00R\x06reload\x12F\n" +
	"\fstream_chunk\x18\x06 \x01(\v2!.nova.agent.v1.StreamChunkPayloadH\x00R\vstreamChunk\"\x89\x01\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_INIT\x10\x01\x12\r\n" +
	"\tTYPE_EXEC\x10\x02\x12\r\n" +
	"\tTYPE_RESP\x10\x03\x12\r\n" +
	"\tTYPE_PING\x10\x04\x12\r\n" +
	"\tTYPE_STOP\x10\x05\x12\x0f\n" +
	"\vTYPE_RELOAD\x10\x06\x12\x0f\n" +
	"\vTYPE_STREAM\x10\aB\t\n" +
	"\apayload\"\xb8\x03\n" +
	"\vInitPayload\x12\x18\n" +
	"\aruntime\x18\x01 \x01(\tR\aruntime\x12\x18\n" +
	"\ahandler\x18\x02 \x01(\tR\ahandler\x12B\n" +
	"\benv_vars\x18\x03 \x03(\v2'.nova.agent.v1.InitPayload.EnvVarsEntryR\aenvVars\x12\x18\n" +
	"\acommand\x18\x04 \x03(\tR\acommand\x12\x1c\n" +
	"\textension\x18\x05 \x01(\tR\textension\x12\x12\n" +
	"\x04mode\x18\x06 \x01(\tR\x04mode\x12#\n" +
	"\rfunction_name\x18\a \x01(\tR\ffunctionName\x12)\n" +
	"\x10function_version\x18\b \x01(\x05R\x0ffunctionVersion\x12\x1b\n" +
	"\tmemory_mb\x18\t \x01(\x05R\bmemoryMb\x12\x1b\n" +
	"\ttimeout_s\x18\n" +
	" \x01(\x05R\btimeoutS\x12\x1f\n" +
	"\vlayer_count\x18\v \x01(\x05R\n" +
	"layerCount\x1a:\n" +
	"\fEnvVarsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbb\x01\n" +
	"\vExecPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12\x1b\n" +
	"\ttimeout_s\x18\x03 \x01(\x05R\btimeoutS\x12!\n" +
	"\ftrace_parent\x18\x04 \x01(\tR\vtraceParent\x12\x1f\n" +
	"\vtrace_state\x18\x05 \x01(\tR\n" +
	"traceState\x12\x16\n" +
	"\x06stream\x18\x06 \x01(\bR\x06stream\"\xab\x01\n" +
	"\vRespPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06stdout\x18\x05 \x01(\tR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x06 \x01(\tR\x06stderr\"\x88\x01\n" +
	"\rReloadPayload\x12=\n" +
	"\x05files\x18\x01 \x03(\v2'.nova.agent.v1.ReloadPayload.FilesEntryR\x05files\x1a8\n" +
	"\n" +
	"FilesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01\"v\n" +
	"\x12StreamChunkPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05errorB)Z'github.com/oriys/nova/api/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_agent_proto_goTypes = []any{
	(VsockMessage_Type)(0),     // 0: nova.agent.v1.VsockMessage.Type
	(*VsockMessage)(nil),       // 1: nova.agent.v1.VsockMessage
	(*InitPayload)(nil),        // 2: nova.agent.v1.InitPayload
	(*ExecPayload)(nil),        // 3: nova.agent.v1.ExecPayload
	(*RespPayload)(nil),        // 4: nova.agent.v1.RespPayload
	(*ReloadPayload)(nil),      // 5: nova.agent.v1.ReloadPayload
	(*StreamChunkPayload)(nil), // 6: nova.agent.v1.StreamChunkPayload
	nil,                        // 7: nova.agent.v1.InitPayload.EnvVarsEntry
	nil,                        // 8: nova.agent.v1.ReloadPayload.FilesEntry
}
var file_agent_proto_depIdxs = []int32{
	0, // 0: nova.agent.v1.VsockMessage.type:type_name -> nova.agent.v1.VsockMessage.Type
	2, // 1: nova.agent.v1.VsockMessage.init:type_name -> nova.agent.v1.InitPayload
	3, // 2: nova.agent.v1.VsockMessage.exec:type_name -> nova.agent.v1.ExecPayload
	4, // 3: nova.agent.v1.VsockMessage.resp:type_name -> nova.agent.v1.RespPayload
	5, // 4: nova.agent.v1.VsockMessage.reload:type_name -> nova.agent.v1.ReloadPayload
	6, // 5: nova.agent.v1.VsockMessage.stream_chunk:type_name -> nova.agent.v1.StreamChunkPayload
	7, // 6: nova.agent.v1.InitPayload.env_vars:type_name -> nova.agent.v1.InitPayload.EnvVarsEntry
	8, // 7: nova.agent.v1.ReloadPayload.files:type_name -> nova.agent.v1.ReloadPayload.FilesEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*VsockMessage_Init)(nil),
		(*VsockMessage_Exec)(nil),
		(*VsockMessage_Resp)(nil),
		(*VsockMessage_Reload)(nil),
		(*VsockMessage_StreamChunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
