// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: nova.proto

package novapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Function name to invoke
	Function string `protobuf:"bytes,1,opt,name=function,proto3" json:"function,omitempty"`
	// JSON payload as bytes
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	// Optional timeout override in seconds (0 = use function default)
	TimeoutS int32 `protobuf:"varint,3,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	// Optional metadata passed as key-value pairs
	Metadata      map[string]string `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeRequest) Reset() {
	*x = InvokeRequest{}
	mi := &file_nova_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeRequest) ProtoMessage() {}

func (x *InvokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeRequest.ProtoReflect.Descriptor instead.
func (*InvokeRequest) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{0}
}

func (x *InvokeRequest) GetFunction() string {
	if x != nil {
		return x.Function
	}
	return ""
}

func (x *InvokeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *InvokeRequest) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *InvokeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InvokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Output        []byte                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	DurationMs    int64                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ColdStart     bool                   `protobuf:"varint,5,opt,name=cold_start,json=coldStart,proto3" json:"cold_start,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeResponse) Reset() {
	*x = InvokeResponse{}
	mi := &file_nova_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeResponse) ProtoMessage() {}

func (x *InvokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeResponse.ProtoReflect.Descriptor instead.
func (*InvokeResponse) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{1}
}

func (x *InvokeResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeResponse) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *InvokeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *InvokeResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *InvokeResponse) GetColdStart() bool {
	if x != nil {
		return x.ColdStart
	}
	return false
}

type InvokeAsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvokeAsyncResponse) Reset() {
	*x = InvokeAsyncResponse{}
	mi := &file_nova_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvokeAsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvokeAsyncResponse) ProtoMessage() {}

func (x *InvokeAsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvokeAsyncResponse.ProtoReflect.Descriptor instead.
func (*InvokeAsyncResponse) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{2}
}

func (x *InvokeAsyncResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *InvokeAsyncResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetFunctionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFunctionRequest) Reset() {
	*x = GetFunctionRequest{}
	mi := &file_nova_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFunctionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFunctionRequest) ProtoMessage() {}

func (x *GetFunctionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFunctionRequest.ProtoReflect.Descriptor instead.
func (*GetFunctionRequest) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{3}
}

func (x *GetFunctionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FunctionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Runtime       string                 `protobuf:"bytes,3,opt,name=runtime,proto3" json:"runtime,omitempty"`
	Handler       string                 `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	MemoryMb      int32                  `protobuf:"varint,5,opt,name=memory_mb,json=memoryMb,proto3" json:"memory_mb,omitempty"`
	TimeoutS      int32                  `protobuf:"varint,6,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	Mode          string                 `protobuf:"bytes,7,opt,name=mode,proto3" json:"mode,omitempty"`
	MinReplicas   int32                  `protobuf:"varint,8,opt,name=min_replicas,json=minReplicas,proto3" json:"min_replicas,omitempty"`
	Version       int32                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionInfo) Reset() {
	*x = FunctionInfo{}
	mi := &file_nova_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInfo) ProtoMessage() {}

func (x *FunctionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInfo.ProtoReflect.Descriptor instead.
func (*FunctionInfo) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FunctionInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionInfo) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *FunctionInfo) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *FunctionInfo) GetMemoryMb() int32 {
	if x != nil {
		return x.MemoryMb
	}
	return 0
}

func (x *FunctionInfo) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *FunctionInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FunctionInfo) GetMinReplicas() int32 {
	if x != nil {
		return x.MinReplicas
	}
	return 0
}

func (x *FunctionInfo) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ListFunctionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsRequest) Reset() {
	*x = ListFunctionsRequest{}
	mi := &file_nova_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsRequest) ProtoMessage() {}

func (x *ListFunctionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsRequest.ProtoReflect.Descriptor instead.
func (*ListFunctionsRequest) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{5}
}

type ListFunctionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Functions     []*FunctionInfo        `protobuf:"bytes,1,rep,name=functions,proto3" json:"functions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFunctionsResponse) Reset() {
	*x = ListFunctionsResponse{}
	mi := &file_nova_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFunctionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFunctionsResponse) ProtoMessage() {}

func (x *ListFunctionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFunctionsResponse.ProtoReflect.Descriptor instead.
func (*ListFunctionsResponse) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{6}
}

func (x *ListFunctionsResponse) GetFunctions() []*FunctionInfo {
	if x != nil {
		return x.Functions
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_nova_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{7}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Components    map[string]string      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_nova_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetComponents() map[string]string {
	if x != nil {
		return x.Components
	}
	return nil
}

type ProxyHTTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Query         string                 `protobuf:"bytes,3,opt,name=query,proto3" json:"query,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyHTTPRequest) Reset() {
	*x = ProxyHTTPRequest{}
	mi := &file_nova_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHTTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHTTPRequest) ProtoMessage() {}

func (x *ProxyHTTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHTTPRequest.ProtoReflect.Descriptor instead.
func (*ProxyHTTPRequest) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{9}
}

func (x *ProxyHTTPRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ProxyHTTPRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ProxyHTTPRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *ProxyHTTPRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProxyHTTPRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type ProxyHTTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StatusCode    int32                  `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProxyHTTPResponse) Reset() {
	*x = ProxyHTTPResponse{}
	mi := &file_nova_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProxyHTTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProxyHTTPResponse) ProtoMessage() {}

func (x *ProxyHTTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nova_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProxyHTTPResponse.ProtoReflect.Descriptor instead.
func (*ProxyHTTPResponse) Descriptor() ([]byte, []int) {
	return file_nova_proto_rawDescGZIP(), []int{10}
}

func (x *ProxyHTTPResponse) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *ProxyHTTPResponse) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *ProxyHTTPResponse) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

var File_nova_proto protoreflect.FileDescriptor

const file_nova_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"nova.proto\x12\anova.v1\"\xe1\x01\n" +
	"\rInvokeRequest\x12\x1a\n" +
	"\bfunction\x18\x01 \x01(\tR\bfunction\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1b\n" +
	"\ttimeout_s\x18\x03 \x01(\x05R\btimeoutS\x12@\n" +
	"\bmetadata\x18\x04 \x03(\v2$.nova.v1.InvokeRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x0eInvokeResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06output\x18\x02 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x03R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"cold_start\x18\x05 \x01(\bR\tcoldStart\"L\n" +
	"\x13InvokeAsyncResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"(\n" +
	"\x12GetFunctionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xf1\x01\n" +
	"\fFunctionInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aruntime\x18\x03 \x01(\tR\aruntime\x12\x18\n" +
	"\ahandler\x18\x04 \x01(\tR\ahandler\x12\x1b\n" +
	"\tmemory_mb\x18\x05 \x01(\x05R\bmemoryMb\x12\x1b\n" +
	"\ttimeout_s\x18\x06 \x01(\x05R\btimeoutS\x12\x12\n" +
	"\x04mode\x18\a \x01(\tR\x04mode\x12!\n" +
	"\fmin_replicas\x18\b \x01(\x05R\vminReplicas\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\"\x16\n" +
	"\x14ListFunctionsRequest\"L\n" +
	"\x15ListFunctionsResponse\x123\n" +
	"\tfunctions\x18\x01 \x03(\v2\x15.nova.v1.FunctionInfoR\tfunctions\"\x14\n" +
	"\x12HealthCheckRequest\"\xba\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12L\n" +
	"\n" +
	"components\x18\x02 \x03(\v2,.nova.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x1a=\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe6\x01\n" +
	"\x10ProxyHTTPRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x14\n" +
	"\x05query\x18\x03 \x01(\tR\x05query\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\x12@\n" +
	"\aheaders\x18\x05 \x03(\v2&.nova.v1.ProxyHTTPRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc7\x01\n" +
	"\x11ProxyHTTPResponse\x12\x1f\n" +
	"\vstatus_code\x18\x01 \x01(\x05R\n" +
	"statusCode\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12A\n" +
	"\aheaders\x18\x03 \x03(\v2'.nova.v1.ProxyHTTPResponse.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xae\x03\n" +
	"\vNovaService\x129\n" +
	"\x06Invoke\x12\x16.nova.v1.InvokeRequest\x1a\x17.nova.v1.InvokeResponse\x12C\n" +
	"\vInvokeAsync\x12\x16.nova.v1.InvokeRequest\x1a\x1c.nova.v1.InvokeAsyncResponse\x12A\n" +
	"\vGetFunction\x12\x1b.nova.v1.GetFunctionRequest\x1a\x15.nova.v1.FunctionInfo\x12N\n" +
	"\rListFunctions\x12\x1d.nova.v1.ListFunctionsRequest\x1a\x1e.nova.v1.ListFunctionsResponse\x12H\n" +
	"\vHealthCheck\x12\x1b.nova.v1.HealthCheckRequest\x1a\x1c.nova.v1.HealthCheckResponse\x12B\n" +
	"\tProxyHTTP\x12\x19.nova.v1.ProxyHTTPRequest\x1a\x1a.nova.v1.ProxyHTTPResponseB(Z&github.com/oriys/nova/api/proto/novapbb\x06proto3"

var (
	file_nova_proto_rawDescOnce sync.Once
	file_nova_proto_rawDescData []byte
)

func file_nova_proto_rawDescGZIP() []byte {
	file_nova_proto_rawDescOnce.Do(func() {
		file_nova_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nova_proto_rawDesc), len(file_nova_proto_rawDesc)))
	})
	return file_nova_proto_rawDescData
}

var file_nova_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_nova_proto_goTypes = []any{
	(*InvokeRequest)(nil),         // 0: nova.v1.InvokeRequest
	(*InvokeResponse)(nil),        // 1: nova.v1.InvokeResponse
	(*InvokeAsyncResponse)(nil),   // 2: nova.v1.InvokeAsyncResponse
	(*GetFunctionRequest)(nil),    // 3: nova.v1.GetFunctionRequest
	(*FunctionInfo)(nil),          // 4: nova.v1.FunctionInfo
	(*ListFunctionsRequest)(nil),  // 5: nova.v1.ListFunctionsRequest
	(*ListFunctionsResponse)(nil), // 6: nova.v1.ListFunctionsResponse
	(*HealthCheckRequest)(nil),    // 7: nova.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),   // 8: nova.v1.HealthCheckResponse
	(*ProxyHTTPRequest)(nil),      // 9: nova.v1.ProxyHTTPRequest
	(*ProxyHTTPResponse)(nil),     // 10: nova.v1.ProxyHTTPResponse
	nil,                           // 11: nova.v1.InvokeRequest.MetadataEntry
	nil,                           // 12: nova.v1.HealthCheckResponse.ComponentsEntry
	nil,                           // 13: nova.v1.ProxyHTTPRequest.HeadersEntry
	nil,                           // 14: nova.v1.ProxyHTTPResponse.HeadersEntry
}
var file_nova_proto_depIdxs = []int32{
	11, // 0: nova.v1.InvokeRequest.metadata:type_name -> nova.v1.InvokeRequest.MetadataEntry
	4,  // 1: nova.v1.ListFunctionsResponse.functions:type_name -> nova.v1.FunctionInfo
	12, // 2: nova.v1.HealthCheckResponse.components:type_name -> nova.v1.HealthCheckResponse.ComponentsEntry
	13, // 3: nova.v1.ProxyHTTPRequest.headers:type_name -> nova.v1.ProxyHTTPRequest.HeadersEntry
	14, // 4: nova.v1.ProxyHTTPResponse.headers:type_name -> nova.v1.ProxyHTTPResponse.HeadersEntry
	0,  // 5: nova.v1.NovaService.Invoke:input_type -> nova.v1.InvokeRequest
	0,  // 6: nova.v1.NovaService.InvokeAsync:input_type -> nova.v1.InvokeRequest
	3,  // 7: nova.v1.NovaService.GetFunction:input_type -> nova.v1.GetFunctionRequest
	5,  // 8: nova.v1.NovaService.ListFunctions:input_type -> nova.v1.ListFunctionsRequest
	7,  // 9: nova.v1.NovaService.HealthCheck:input_type -> nova.v1.HealthCheckRequest
	9,  // 10: nova.v1.NovaService.ProxyHTTP:input_type -> nova.v1.ProxyHTTPRequest
	1,  // 11: nova.v1.NovaService.Invoke:output_type -> nova.v1.InvokeResponse
	2,  // 12: nova.v1.NovaService.InvokeAsync:output_type -> nova.v1.InvokeAsyncResponse
	4,  // 13: nova.v1.NovaService.GetFunction:output_type -> nova.v1.FunctionInfo
	6,  // 14: nova.v1.NovaService.ListFunctions:output_type -> nova.v1.ListFunctionsResponse
	8,  // 15: nova.v1.NovaService.HealthCheck:output_type -> nova.v1.HealthCheckResponse
	10, // 16: nova.v1.NovaService.ProxyHTTP:output_type -> nova.v1.ProxyHTTPResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_nova_proto_init() }
func file_nova_proto_init() {
	if File_nova_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nova_proto_rawDesc), len(file_nova_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nova_proto_goTypes,
		DependencyIndexes: file_nova_proto_depIdxs,
		MessageInfos:      file_nova_proto_msgTypes,
	}.Build()
	File_nova_proto = out.File
	file_nova_proto_goTypes = nil
	file_nova_proto_depIdxs = nil
}
