// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.4
// source: nova.proto

package novapb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NovaService_Invoke_FullMethodName        = "/nova.v1.NovaService/Invoke"
	NovaService_InvokeAsync_FullMethodName   = "/nova.v1.NovaService/InvokeAsync"
	NovaService_GetFunction_FullMethodName   = "/nova.v1.NovaService/GetFunction"
	NovaService_ListFunctions_FullMethodName = "/nova.v1.NovaService/ListFunctions"
	NovaService_HealthCheck_FullMethodName   = "/nova.v1.NovaService/HealthCheck"
)

// NovaServiceClient is the client API for NovaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Nova serverless function invocation service
type NovaServiceClient interface {
	// Invoke calls a function synchronously and returns the result
	Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error)
	// InvokeAsync calls a function asynchronously and returns a request ID
	InvokeAsync(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeAsyncResponse, error)
	// GetFunction returns function metadata
	GetFunction(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*FunctionInfo, error)
	// ListFunctions returns all registered functions
	ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error)
	// HealthCheck returns service health status
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type novaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNovaServiceClient(cc grpc.ClientConnInterface) NovaServiceClient {
	return &novaServiceClient{cc}
}

func (c *novaServiceClient) Invoke(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeResponse)
	err := c.cc.Invoke(ctx, NovaService_Invoke_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaServiceClient) InvokeAsync(ctx context.Context, in *InvokeRequest, opts ...grpc.CallOption) (*InvokeAsyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InvokeAsyncResponse)
	err := c.cc.Invoke(ctx, NovaService_InvokeAsync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaServiceClient) GetFunction(ctx context.Context, in *GetFunctionRequest, opts ...grpc.CallOption) (*FunctionInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FunctionInfo)
	err := c.cc.Invoke(ctx, NovaService_GetFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaServiceClient) ListFunctions(ctx context.Context, in *ListFunctionsRequest, opts ...grpc.CallOption) (*ListFunctionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListFunctionsResponse)
	err := c.cc.Invoke(ctx, NovaService_ListFunctions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *novaServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, NovaService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NovaServiceServer is the server API for NovaService service.
// All implementations must embed UnimplementedNovaServiceServer
// for forward compatibility.
//
// Nova serverless function invocation service
type NovaServiceServer interface {
	// Invoke calls a function synchronously and returns the result
	Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error)
	// InvokeAsync calls a function asynchronously and returns a request ID
	InvokeAsync(context.Context, *InvokeRequest) (*InvokeAsyncResponse, error)
	// GetFunction returns function metadata
	GetFunction(context.Context, *GetFunctionRequest) (*FunctionInfo, error)
	// ListFunctions returns all registered functions
	ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error)
	// HealthCheck returns service health status
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedNovaServiceServer()
}

// UnimplementedNovaServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNovaServiceServer struct{}

func (UnimplementedNovaServiceServer) Invoke(context.Context, *InvokeRequest) (*InvokeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Invoke not implemented")
}
func (UnimplementedNovaServiceServer) InvokeAsync(context.Context, *InvokeRequest) (*InvokeAsyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InvokeAsync not implemented")
}
func (UnimplementedNovaServiceServer) GetFunction(context.Context, *GetFunctionRequest) (*FunctionInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFunction not implemented")
}
func (UnimplementedNovaServiceServer) ListFunctions(context.Context, *ListFunctionsRequest) (*ListFunctionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListFunctions not implemented")
}
func (UnimplementedNovaServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNovaServiceServer) mustEmbedUnimplementedNovaServiceServer() {}
func (UnimplementedNovaServiceServer) testEmbeddedByValue()                     {}

// UnsafeNovaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NovaServiceServer will
// result in compilation errors.
type UnsafeNovaServiceServer interface {
	mustEmbedUnimplementedNovaServiceServer()
}

func RegisterNovaServiceServer(s grpc.ServiceRegistrar, srv NovaServiceServer) {
	// If the following call panics, it indicates UnimplementedNovaServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NovaService_ServiceDesc, srv)
}

func _NovaService_Invoke_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServiceServer).Invoke(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovaService_Invoke_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServiceServer).Invoke(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovaService_InvokeAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InvokeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServiceServer).InvokeAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovaService_InvokeAsync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServiceServer).InvokeAsync(ctx, req.(*InvokeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovaService_GetFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServiceServer).GetFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovaService_GetFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServiceServer).GetFunction(ctx, req.(*GetFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovaService_ListFunctions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFunctionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServiceServer).ListFunctions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovaService_ListFunctions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServiceServer).ListFunctions(ctx, req.(*ListFunctionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NovaService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NovaServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NovaService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NovaServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NovaService_ServiceDesc is the grpc.ServiceDesc for NovaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NovaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nova.v1.NovaService",
	HandlerType: (*NovaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invoke",
			Handler:    _NovaService_Invoke_Handler,
		},
		{
			MethodName: "InvokeAsync",
			Handler:    _NovaService_InvokeAsync_Handler,
		},
		{
			MethodName: "GetFunction",
			Handler:    _NovaService_GetFunction_Handler,
		},
		{
			MethodName: "ListFunctions",
			Handler:    _NovaService_ListFunctions_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _NovaService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nova.proto",
}
